version: '3.3'
services:
  wisdom-flow-frontend:
    container_name: wisdom-flow-frontend
    build: .
    image: wisdom-flow-frontend
    restart: always
    env_file:
      - ./.env
    ports:
      - "${EXPORT_PORT}:3000"
