version: "3.5"

services:
  wisdom-flow-frontend:
    image: nginx:1.15
    container_name: wisdom-flow-frontend
    env_file:
      - .env
    ports:
      - "${EXPORT_PORT}:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./dist:/var/www/html